# Generated by Django 5.0.3 on 2024-05-09 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SellPurchase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
